FROM tensorflow/tensorflow:1.13.2-gpu-py3-jupyter

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y ffmpeg
RUN apt-get install -y vim
RUN apt-get install -y libsm6 libxext6 libxrender-dev

WORKDIR /

RUN git clone https://github.com/Rudrabha/Lip2Wav.git

WORKDIR Lip2Wav

RUN pip install --upgrade pip
RUN pip install Cython
RUN pip install numba==0.48.0
RUN pip uninstall -y enum34
RUN pip install -r requirements.txt

